name: pubel
description: A new Flutter project for sharing files to PC.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  network_info_plus: ^5.0.0
  file_picker: ^8.0.0
  google_fonts: ^6.1.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
